### PR TITLE
Create PollutedLocationDTO type

### LINKED ISSUE #1: Create PollutedLocationDTO type
## Description

Create a `PollutedLocationDTO` type for later use in components. This type will represent the PollutedLocation JSON coming in from/sending to the backend.

## Steps to take

1. Create a types folder `/src/types/`
2. Create a folder for back end models/types `/src/types/backEnd`
3. Create a file for `PollutedLocationDTO.ts` type
4. Define the Typescript `type` with properties that we decided in vu-vibedosa/apsitvarkom-be#4. Refer to [Everyday types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html) and [tutorials such as this](https://www.digitalocean.com/community/tutorials/how-to-create-custom-types-in-typescript)
5. Don't forget to export that type in the file

## Acceptance criteria

Type `PollutedLocationDTO` created in `/src/types/backEnd` that contains fields we discussed earlier.

### PR DESCRIPTION
**Pull request by 6ar8nas**
## What was done

- Created PollutedLocationDTO and LocationDTO types

### CODE REVIEW

**Comment by 6ar8nas** [comment]
We will need to adjust the documentation after implementing the PollutedLocation and Location equivalents if the names could change (and I believe they will change, as Location is a used name already).

**Review by BenasB — CHANGES_REQUESTED** [review]
Instead of adding `?` to each field, you can wrap the type in a [Partial<T> type](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) which will achieve the same thing. Otherwise looks good

**Comment by BenasB** [comment]
TIL about writing [JSDoc](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html)

**Review by BenasB — CHANGES_REQUESTED** [review]
`LocationDTO` still contains `?` and I expected the types to be wrapped in a `Partial` when exporting it, example:

```Typescript
export type MyPartialType = Partial<{
    myField: string;
}>
```

**Review by BenasB — APPROVED** [review]
LGTM, feel free to merge

**Pull request merged**
